feat: enhance CI workflow to include ps1 restart and health checks; add replica before remove

diff --git a/.github/workflows/CI_cluster.yml b/.github/workflows/CI_cluster.yml
--- a/.github/workflows/CI_cluster.yml
+++ b/.github/workflows/CI_cluster.yml
@@ -204,6 +204,13 @@ jobs:
         sleep 10
         docker-compose -f cloud/docker-compose.yml stop ps1
         sleep 60
+        docker-compose -f cloud/docker-compose.yml start ps1
+        sleep 60
+        status=$(curl -s -L -u root:secret http://127.0.0.1:8817/servers 2>/dev/null | jq -r '.data.servers[] | select(.server.ip == "172.16.238.16") | .partitions | length == 0')
+        if [ "$status" != "true" ]; then
+          echo "Error: ps1 partitions num should be 0."
+          exit 1
+        fi
         status=$(curl -u root:secret http://127.0.0.1:8817/cluster/health | jq -r '.data[0].spaces[0].status')
         if [ "$status" != "green" ]; then
           echo "Error: Status is not green. Status is $status."
@@ -213,7 +220,6 @@ jobs:
         fi
         cd test && pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
         cd .. && docker-compose -f cloud/docker-compose.yml down ps4
-        docker-compose -f cloud/docker-compose.yml start ps1
         sleep 60 && docker ps
   
     - name: Run tests for master replace member
